image: ubuntu
build_script:
- ps: ./package.ps1
artifacts:
- path: 'artifacts\replays.zip'
deploy:
  provider: GitHub
  auth_token:
    secure: uXuMd3cu0eDp/Sz+XPaIVyROW36oLcxY0u72smAOAcn6LSViamfbxf9WpgcxQp1z
  artifact: artifacts\replays.zip
  draft: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
