name: CI
on: [push, pull_request]
defaults:
  run:
    shell: pwsh
jobs:
  package_replays:
    name: Package Replays
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package Replays
        run: ./package.ps1
        id: package
      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v4
        with:
          name: replays
          path: artifacts/replays.zip
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: SHA1:${{ steps.package.outputs.SHA1 }}
          files: artifacts/replays.zip
